webtalk_init -webtalk_dir /home/srihari/Hardware_securiy/Metastability_final_with-PI/sdk_fix/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun May 1 18:50:03 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174679548_176449548_210570730_342" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "qthear4o65nj0ih5390h5pojvq" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_15" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "782.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1462136518000" -context "sdk\\\\hardware/1462136518000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1462136518000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1462136518000"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1462136518000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1462136518000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1462136518000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1462136518000"
webtalk_transmit -clientid 3209880356 -regid "174679548_176449548_210570730_342" -xml /home/srihari/Hardware_securiy/Metastability_final_with-PI/sdk_fix/webtalk/usage_statistics_ext_sdk.xml -html /home/srihari/Hardware_securiy/Metastability_final_with-PI/sdk_fix/webtalk/usage_statistics_ext_sdk.html -wdm /home/srihari/Hardware_securiy/Metastability_final_with-PI/sdk_fix/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
