webtalk_init -webtalk_dir /home/srihari/Hardware_securiy/UART_arm_core/Fiagaro_data_collect/de_bias.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr 18 19:59:32 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174679548_176449548_210570730_342" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "rs9p6ir3ontemki1t1uehgrog1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "782.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1461022586000" -context "sdk\\\\hardware/1461022586000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1461022586000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1461022586000"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1461022586000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1461022586000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1461022586000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1461022586000"
webtalk_add_data -client sdk -key uid -value "1461022643000" -context "sdk\\\\bsp/1461022643000"
webtalk_add_data -client sdk -key hwid -value "1461022586000" -context "sdk\\\\bsp/1461022643000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1461022643000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1461022643000"
webtalk_add_data -client sdk -key uid -value "1461022646000" -context "sdk\\\\application/1461022646000"
webtalk_add_data -client sdk -key hwid -value "1461022586000" -context "sdk\\\\application/1461022646000"
webtalk_add_data -client sdk -key bspid -value "1461022643000" -context "sdk\\\\application/1461022646000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1461022646000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1461022646000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1461022646000"
webtalk_transmit -clientid 1383261668 -regid "174679548_176449548_210570730_342" -xml /home/srihari/Hardware_securiy/UART_arm_core/Fiagaro_data_collect/de_bias.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/srihari/Hardware_securiy/UART_arm_core/Fiagaro_data_collect/de_bias.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/srihari/Hardware_securiy/UART_arm_core/Fiagaro_data_collect/de_bias.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
