set_property IOSTANDARD LVCMOS25 [get_ports {LED0_T22[0]}]
set_property DIFF_TERM FALSE [get_ports {LED0_T22[0]}]
set_property PACKAGE_PIN T22 [get_ports {LED0_T22[0]}]


set_property IOSTANDARD LVCMOS25 [get_ports registered_data_LED2_u21]
set_property DIFF_TERM FALSE [get_ports registered_data_LED2_u21]
set_property PACKAGE_PIN U21 [get_ports registered_data_LED2_u21]

set_property IOSTANDARD LVCMOS25 [get_ports {uart_complete_led_G22[0]}]
set_property DIFF_TERM FALSE [get_ports {uart_complete_led_G22[0]}]
set_property PACKAGE_PIN W22 [get_ports {uart_complete_led_G22[0]}]

set_property IOSTANDARD LVCMOS25 [get_ports registered_negedge_U14]
set_property DIFF_TERM FALSE [get_ports registered_negedge_U14]
set_property PACKAGE_PIN U14 [get_ports registered_negedge_U14]

set_property IOSTANDARD LVCMOS25 [get_ports enable_bram_interrupt]
set_property DIFF_TERM FALSE [get_ports enable_bram_interrupt]
set_property PACKAGE_PIN F22 [get_ports enable_bram_interrupt]

#set_false_path -from [get_pins metastable_ro_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT0] -to [get_pins metastable_ro_i/delay_top_0/inst/registered_out_reg/D]
#set_false_path -from [get_pins metastable_ro_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT0] -to [get_pins metastable_ro_i/delay_top_0/inst/registered_negedge_out_reg/D]
#set_false_path -from [get_clocks clk_out1_metastable_ro_clk_wiz_0_0] -to [get_clocks clk_fpga_0]


set_property IOSTANDARD LVCMOS25 [get_ports {DIP_CLOCKS_TO_LOAD[0]}]
set_property DIFF_TERM FALSE [get_ports {DIP_CLOCKS_TO_LOAD[0]}]
set_property PACKAGE_PIN M15 [get_ports {DIP_CLOCKS_TO_LOAD[0]}]

set_property IOSTANDARD LVCMOS25 [get_ports {DIP_CLOCKS_TO_LOAD[1]}]
set_property DIFF_TERM FALSE [get_ports {DIP_CLOCKS_TO_LOAD[1]}]
set_property PACKAGE_PIN H17 [get_ports {DIP_CLOCKS_TO_LOAD[1]}]

set_property IOSTANDARD LVCMOS25 [get_ports {DIP_CLOCKS_TO_LOAD[2]}]
set_property DIFF_TERM FALSE [get_ports {DIP_CLOCKS_TO_LOAD[2]}]
set_property PACKAGE_PIN H18 [get_ports {DIP_CLOCKS_TO_LOAD[2]}]

set_property IOSTANDARD LVCMOS25 [get_ports {DIP_CLOCKS_TO_LOAD[3]}]
set_property DIFF_TERM FALSE [get_ports {DIP_CLOCKS_TO_LOAD[3]}]
set_property PACKAGE_PIN H19 [get_ports {DIP_CLOCKS_TO_LOAD[3]}]

set_property IOSTANDARD LVCMOS25 [get_ports {DIP_CLOCKS_TO_LOAD[4]}]
set_property DIFF_TERM FALSE [get_ports {DIP_CLOCKS_TO_LOAD[4]}]
set_property PACKAGE_PIN F21 [get_ports {DIP_CLOCKS_TO_LOAD[4]}]

set_property IOSTANDARD LVCMOS25 [get_ports {DIP_CLOCKS_TO_LOAD[5]}]
set_property DIFF_TERM FALSE [get_ports {DIP_CLOCKS_TO_LOAD[5]}]
set_property PACKAGE_PIN H22 [get_ports {DIP_CLOCKS_TO_LOAD[5]}]


set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[31].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X40Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[31].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[27].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X41Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[27].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[23].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X42Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[23].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[19].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X43Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[19].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[15].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X44Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[15].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[11].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X45Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[11].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[7].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X46Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[7].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[3].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X47Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[3].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[30].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X40Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[30].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[26].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X41Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[26].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[22].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X42Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[22].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[18].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X43Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[18].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[14].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X44Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[14].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[10].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X45Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[10].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[6].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X46Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[6].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[2].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X47Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[2].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[29].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X40Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[29].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[25].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X41Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[25].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[21].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X42Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[21].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[17].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X43Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[17].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[13].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X44Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[13].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[9].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X45Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[9].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[5].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X46Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[5].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[1].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X47Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[1].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[28].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X40Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[28].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[24].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X41Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[24].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[20].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X42Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[20].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[16].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X43Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[16].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[12].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X44Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[12].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[8].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X45Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[8].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[4].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X46Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[4].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[0].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X47Y103 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[0].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[31].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X40Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[31].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[27].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X41Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[27].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[23].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X42Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[23].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[19].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X43Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[19].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[15].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X44Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[15].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[11].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X45Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[11].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[7].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X46Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[7].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[3].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X47Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[3].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[30].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X40Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[30].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[26].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X41Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[26].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[22].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X42Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[22].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[18].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X43Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[18].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[14].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X44Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[14].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[10].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X45Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[10].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[6].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X46Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[6].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[2].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X47Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[2].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[29].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X40Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[29].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[25].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X41Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[25].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[21].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X42Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[21].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[17].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X43Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[17].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[13].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X44Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[13].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[9].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X45Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[9].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[5].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X46Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[5].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[1].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X47Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[1].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[28].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X40Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[28].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[24].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X41Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[24].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[20].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X42Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[20].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[16].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X43Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[16].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[12].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X44Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[12].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[8].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X45Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[8].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[4].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X46Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[4].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[0].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X47Y104 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[0].lut_coarse_delay_inst_data/LUT6_inst}]

#set_property BEL B6LUT [get_cells metastable_ro_i/delay_top_0/inst/coarse_delay_inst/i_0]
#set_property LOC SLICE_X39Y101 [get_cells metastable_ro_i/delay_top_0/inst/coarse_delay_inst/i_0]
#set_property BEL C6LUT [get_cells metastable_ro_i/delay_top_0/inst/LUT1_input_buf_anchor]
#set_property LOC SLICE_X39Y101 [get_cells metastable_ro_i/delay_top_0/inst/LUT1_input_buf_anchor]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[63].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X40Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[63].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[59].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X41Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[59].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[55].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X42Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[55].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[51].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X43Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[51].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[47].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X44Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[47].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[43].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X45Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[43].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[39].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X46Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[39].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[35].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X47Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[35].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[62].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X40Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[62].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[58].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X41Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[58].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[54].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X42Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[54].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[50].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X43Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[50].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[46].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X44Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[46].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[42].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X45Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[42].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[38].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X46Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[38].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[34].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X47Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[34].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[61].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X40Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[61].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[57].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X41Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[57].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[53].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X42Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[53].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[49].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X43Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[49].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[45].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X44Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[45].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[41].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X45Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[41].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[37].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X46Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[37].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[33].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X47Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[33].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[60].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X40Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[60].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[56].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X41Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[56].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[52].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X42Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[52].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[48].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X43Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[48].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[44].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X44Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[44].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[40].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X45Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[40].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[36].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X46Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[36].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[32].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOC SLICE_X47Y101 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[32].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[63].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X40Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[63].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[59].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X41Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[59].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[55].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X42Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[55].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[51].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X43Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[51].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[47].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X44Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[47].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[43].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X45Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[43].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[39].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X46Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[39].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL A6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[35].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X47Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[35].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[62].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X40Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[62].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[58].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X41Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[58].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[54].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X42Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[54].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[50].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X43Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[50].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[46].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X44Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[46].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[42].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X45Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[42].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[38].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X46Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[38].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL B6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[34].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X47Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[34].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[61].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X40Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[61].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[57].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X41Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[57].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[53].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X42Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[53].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[49].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X43Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[49].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[45].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X44Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[45].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[41].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X45Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[41].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[37].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X46Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[37].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL C6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[33].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X47Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[33].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[60].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X40Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[60].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[56].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X41Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[56].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[52].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X42Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[52].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[48].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X43Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[48].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[44].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X44Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[44].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[40].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X45Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[40].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[36].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X46Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[36].lut_coarse_delay_inst_data/LUT6_inst}]


set_property BEL D6LUT [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[32].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOC SLICE_X47Y102 [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[32].lut_coarse_delay_inst_data/LUT6_inst}]
set_property BEL BFF [get_cells metastable_ro_i/delay_top_0/inst/registered_out_reg]
set_property LOC SLICE_X48Y104 [get_cells metastable_ro_i/delay_top_0/inst/registered_out_reg]
set_property BEL BFF [get_cells metastable_ro_i/delay_top_0/inst/registered_negedge_out_reg]
set_property LOC SLICE_X49Y104 [get_cells metastable_ro_i/delay_top_0/inst/registered_negedge_out_reg]



set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[63].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A2 I3:A3 I4:A4 I5:A1} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[62].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[61].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[60].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A3 I1:A1 I2:A2 I3:A4 I4:A5 I5:A6} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[63].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A2 I3:A3 I4:A4 I5:A1} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[62].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[61].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[60].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[31].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A1 I2:A2 I3:A3 I4:A4 I5:A6} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[30].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A1 I2:A2 I3:A3 I4:A4 I5:A6} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[29].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[28].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[31].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[30].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[29].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[28].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A3 I2:A6 I3:A2 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[24].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[23].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[25].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[26].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A6 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[27].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A4 I1:A1 I2:A2 I3:A3 I4:A6 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[24].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[25].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[26].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A6 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[27].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[56].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[57].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A2 I2:A1 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[58].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A4 I1:A6 I2:A2 I3:A3 I4:A1 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[59].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[56].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[57].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[58].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A2 I1:A6 I2:A1 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[59].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[55].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A2 I3:A3 I4:A4 I5:A1} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[54].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[53].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[52].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[55].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[54].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[53].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[52].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[21].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[22].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[20].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[16].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[17].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A1 I2:A2 I3:A3 I4:A4 I5:A6} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[18].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A1 I2:A2 I3:A3 I4:A4 I5:A6} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[19].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[16].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[17].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A1 I2:A6 I3:A3 I4:A2 I5:A4} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[18].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A1 I2:A2 I3:A3 I4:A4 I5:A6} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[19].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A4 I1:A1 I2:A2 I3:A3 I4:A6 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[48].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[49].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[50].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A1 I2:A2 I3:A3 I4:A4 I5:A6} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[51].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A4 I1:A1 I2:A2 I3:A6 I4:A3 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[48].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[49].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A2 I3:A3 I4:A1 I5:A4} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[50].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A6 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[51].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[47].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A1 I2:A2 I3:A3 I4:A6 I5:A4} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[46].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[45].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A3 I1:A1 I2:A2 I3:A6 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[44].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[47].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A1 I2:A2 I3:A3 I4:A4 I5:A6} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[46].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[45].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A4 I1:A1 I2:A2 I3:A3 I4:A6 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[44].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[15].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A1 I2:A2 I3:A3 I4:A4 I5:A6} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[14].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[13].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[12].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[15].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A1 I2:A6 I3:A3 I4:A4 I5:A2} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[14].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[13].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A4 I1:A1 I2:A2 I3:A3 I4:A6 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[12].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A4 I1:A1 I2:A2 I3:A3 I4:A6 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[8].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[9].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A1 I2:A2 I3:A3 I4:A4 I5:A6} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[10].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A2 I1:A6 I2:A1 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[11].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A4 I1:A1 I2:A2 I3:A6 I4:A3 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[8].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[9].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[10].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A2 I1:A6 I2:A1 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[11].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A4 I1:A6 I2:A2 I3:A3 I4:A1 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[40].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[41].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[42].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A4 I1:A6 I2:A2 I3:A3 I4:A1 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[43].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[40].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[41].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A2 I3:A3 I4:A4 I5:A1} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[42].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[43].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[39].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A2 I3:A3 I4:A4 I5:A1} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[38].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[37].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[36].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[39].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A1 I3:A3 I4:A4 I5:A2} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[38].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[37].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[36].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[7].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[6].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A6 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[5].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[4].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A3 I1:A1 I2:A2 I3:A6 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[7].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[6].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[5].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A4 I1:A1 I2:A2 I3:A3 I4:A6 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[4].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[0].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[1].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A1 I2:A6 I3:A3 I4:A4 I5:A2} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[2].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4 I3:A3 I4:A6 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[3].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A4 I1:A1 I2:A2 I3:A6 I4:A3 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[0].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[1].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A2 I2:A1 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[2].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[3].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A1 I1:A6 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[32].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[33].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A2 I1:A6 I2:A1 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[34].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A4 I1:A1 I2:A2 I3:A3 I4:A6 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[35].lut_coarse_delay_inst_data/LUT6_inst}]
set_property LOCK_PINS {I0:A4 I1:A1 I2:A2 I3:A3 I4:A6 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[32].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A3 I1:A6 I2:A2 I3:A1 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[33].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A6 I2:A2 I3:A3 I4:A4 I5:A1} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[34].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A1 I2:A2 I3:A3 I4:A4 I5:A6} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[35].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property BEL C6LUT [get_cells metastable_ro_i/delay_top_0/inst/i_0]
set_property LOC SLICE_X48Y104 [get_cells metastable_ro_i/delay_top_0/inst/i_0]
set_property FIXED_ROUTE { { CLBLM_L_D CLBLM_LOGIC_OUTS11 NL1BEG2 EL1BEG1 SL1BEG1  { BYP_ALT5 BYP_L5 CLBLL_L_BX }  BYP_ALT4 BYP_L4 CLBLL_LL_BX }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[0].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_L_CMUX CLBLM_LOGIC_OUTS18 IMUX41 CLBLM_L_D1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[1].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 IMUX34 CLBLM_L_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[2].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[3].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_D CLBLM_M_DMUX CLBLM_LOGIC_OUTS23 IMUX3 CLBLM_L_A2 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[4].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 IMUX44 CLBLM_M_D4 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[5].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 IMUX35 CLBLM_M_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[6].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_M_AMUX CLBLM_LOGIC_OUTS20 IMUX12 CLBLM_M_B6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[7].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_D CLBLL_L_DMUX CLBLL_LOGIC_OUTS19 EL1BEG0 IMUX1 CLBLM_M_A3 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[8].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10 IMUX_L37 CLBLL_L_D4 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[9].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_B CLBLL_LOGIC_OUTS9 IMUX_L34 CLBLL_L_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[10].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_A CLBLL_LOGIC_OUTS8 IMUX_L25 CLBLL_L_B5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[11].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_D CLBLL_LL_DMUX CLBLL_LOGIC_OUTS23 IMUX_L3 CLBLL_L_A2 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[12].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14 IMUX_L44 CLBLL_LL_D4 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[13].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 IMUX_L35 CLBLL_LL_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[14].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[15].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_D CLBLM_LOGIC_OUTS11 EL1BEG2 IMUX_L4 CLBLL_LL_A6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[16].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_L_CMUX CLBLM_LOGIC_OUTS18 IMUX41 CLBLM_L_D1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[17].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 IMUX34 CLBLM_L_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[18].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[19].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_D CLBLM_LOGIC_OUTS15 SR1BEG_S0 IMUX9 CLBLM_L_A5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[20].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_M_CMUX CLBLM_LOGIC_OUTS22 IMUX40 CLBLM_M_D1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[21].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 IMUX35 CLBLM_M_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[22].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 NW2BEG0 EL1BEG_N3 IMUX15 CLBLM_M_B1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[23].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_D CLBLL_LOGIC_OUTS11 SE2BEG3 NR1BEG3 IMUX7 CLBLM_M_A1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[24].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_L_CMUX CLBLL_LOGIC_OUTS18 IMUX_L41 CLBLL_L_D1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[25].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_B CLBLL_LOGIC_OUTS9 IMUX_L34 CLBLL_L_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[26].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_A CLBLL_L_AMUX CLBLL_LOGIC_OUTS16 IMUX_L13 CLBLL_L_B6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[27].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_D CLBLL_LL_DMUX CLBLL_LOGIC_OUTS23 IMUX_L3 CLBLL_L_A2 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[28].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LL_CMUX CLBLL_LOGIC_OUTS22 IMUX_L40 CLBLL_LL_D1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[29].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 IMUX_L35 CLBLL_LL_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[30].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LL_AMUX CLBLL_LOGIC_OUTS20 IMUX_L12 CLBLL_LL_B6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[31].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_D CLBLM_LOGIC_OUTS11 NW2BEG3 WL1BEG1 NW2BEG2 IMUX_L4 CLBLL_LL_A6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[32].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_L_CMUX CLBLM_LOGIC_OUTS18 IMUX41 CLBLM_L_D1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[33].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 IMUX34 CLBLM_L_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[34].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_L_AMUX CLBLM_LOGIC_OUTS16 FAN_ALT5 FAN_BOUNCE5 IMUX19 CLBLM_L_B2 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[35].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_D CLBLM_LOGIC_OUTS15 SR1BEG_S0 IMUX10 CLBLM_L_A4 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[36].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_M_CMUX CLBLM_LOGIC_OUTS22 IMUX40 CLBLM_M_D1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[37].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 IMUX35 CLBLM_M_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[38].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[39].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_D CLBLL_LOGIC_OUTS11 EL1BEG2 IMUX4 CLBLM_M_A6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[40].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10 IMUX_L37 CLBLL_L_D4 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[41].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_B CLBLL_LOGIC_OUTS9 IMUX_L34 CLBLL_L_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[42].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_A CLBLL_L_AMUX CLBLL_LOGIC_OUTS16 IMUX_L13 CLBLL_L_B6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[43].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_D CLBLL_LOGIC_OUTS15 SR1BEG_S0 IMUX_L10 CLBLL_L_A4 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[44].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14 IMUX_L44 CLBLL_LL_D4 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[45].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 IMUX_L35 CLBLL_LL_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[46].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[47].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_D CLBLM_LOGIC_OUTS11 EL1BEG2 IMUX_L4 CLBLL_LL_A6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[48].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10 IMUX37 CLBLM_L_D4 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[49].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 IMUX34 CLBLM_L_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[50].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 NL1BEG_N3 IMUX14 CLBLM_L_B1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[51].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_D CLBLM_LOGIC_OUTS15 SW2BEG3 ER1BEG_S0 IMUX9 CLBLM_L_A5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[52].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_M_CMUX CLBLM_LOGIC_OUTS22 IMUX40 CLBLM_M_D1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[53].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SR1BEG2 BYP_ALT6 BYP_BOUNCE6 IMUX32 CLBLM_M_C1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[54].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 NW2BEG0 EL1BEG_N3 IMUX15 CLBLM_M_B1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[55].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_D CLBLL_LOGIC_OUTS11 EL1BEG2 IMUX4 CLBLM_M_A6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[56].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_L_CMUX CLBLL_LOGIC_OUTS18 IMUX_L41 CLBLL_L_D1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[57].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_B CLBLL_LOGIC_OUTS9 IMUX_L34 CLBLL_L_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[58].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_A CLBLL_L_AMUX CLBLL_LOGIC_OUTS16 IMUX_L13 CLBLL_L_B6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[59].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_D CLBLL_LOGIC_OUTS15 SR1BEG_S0 IMUX_L10 CLBLL_L_A4 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[60].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LL_CMUX CLBLL_LOGIC_OUTS22 IMUX_L40 CLBLL_LL_D1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[61].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 IMUX_L35 CLBLL_LL_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[62].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[63].lut_coarse_delay_inst_data/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_D CLBLM_LOGIC_OUTS11 NR1BEG3  { NN2BEG3 EL1BEG2 SS2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L1 CLBLL_LL_CLK }  EL1BEG2 IMUX_L35 CLBLL_LL_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[0].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10 IMUX37 CLBLM_L_D4 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[1].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 IMUX34 CLBLM_L_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[2].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_L_AMUX CLBLM_LOGIC_OUTS16 IMUX13 CLBLM_L_B6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[3].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_D CLBLM_LOGIC_OUTS15 NE2BEG3 SL1BEG3 WL1BEG2 IMUX6 CLBLM_L_A1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[4].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_M_CMUX CLBLM_LOGIC_OUTS22 IMUX40 CLBLM_M_D1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[5].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 NW2BEG1 SR1BEG1 ER1BEG2 IMUX29 CLBLM_M_C2 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[6].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_M_AMUX CLBLM_LOGIC_OUTS20 IMUX12 CLBLM_M_B6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[7].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_D CLBLL_LOGIC_OUTS11 SE2BEG3 NR1BEG3 IMUX7 CLBLM_M_A1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[8].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10 IMUX_L37 CLBLL_L_D4 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[9].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_B CLBLL_LOGIC_OUTS9 IMUX_L34 CLBLL_L_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[10].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_A CLBLL_L_AMUX CLBLL_LOGIC_OUTS16 IMUX_L13 CLBLL_L_B6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[11].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_D CLBLL_LL_DMUX CLBLL_LOGIC_OUTS23 IMUX_L3 CLBLL_L_A2 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[12].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LL_CMUX CLBLL_LOGIC_OUTS22 IMUX_L40 CLBLL_LL_D1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[13].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 NE2BEG1 SL1BEG1 WL1BEG0 IMUX_L32 CLBLL_LL_C1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[14].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[15].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_D CLBLM_LOGIC_OUTS11 EL1BEG2 IMUX_L4 CLBLL_LL_A6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[16].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_L_CMUX CLBLM_LOGIC_OUTS18 IMUX41 CLBLM_L_D1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[17].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 IMUX34 CLBLM_L_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[18].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[19].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_D CLBLM_LOGIC_OUTS15 SR1BEG_S0 IMUX9 CLBLM_L_A5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[20].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 IMUX44 CLBLM_M_D4 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[21].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 IMUX35 CLBLM_M_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[22].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[23].lut_coarse_delay_inst_clk/inv_data}]
set_property LOCK_PINS {I0:A3 I1:A1 I2:A2 I3:A6 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[23].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A5 I1:A1 I2:A2 I3:A3 I4:A6 I5:A4} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[22].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A2 I3:A3 I4:A4 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[21].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A4 I1:A1 I2:A2 I3:A3 I4:A6 I5:A5} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[20].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property FIXED_ROUTE { { CLBLL_L_D CLBLL_L_DMUX CLBLL_LOGIC_OUTS19 EL1BEG0 IMUX1 CLBLM_M_A3 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[24].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10 IMUX_L37 CLBLL_L_D4 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[25].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_B CLBLL_LOGIC_OUTS9 IMUX_L34 CLBLL_L_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[26].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_A CLBLL_L_AMUX CLBLL_LOGIC_OUTS16 IMUX_L13 CLBLL_L_B6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[27].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LL_CMUX CLBLL_LOGIC_OUTS22 IMUX_L40 CLBLL_LL_D1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[29].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LL_BMUX CLBLL_LOGIC_OUTS21 IMUX_L31 CLBLL_LL_C5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[30].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[31].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_D CLBLM_LOGIC_OUTS11 NE2BEG3 WW4BEG3 NL1BEG2 IMUX_L4 CLBLL_LL_A6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[32].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10 IMUX37 CLBLM_L_D4 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[33].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 NL1BEG0 IMUX23 CLBLM_L_C3 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[34].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[35].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_D CLBLM_LOGIC_OUTS15 SR1BEG_S0 IMUX9 CLBLM_L_A5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[36].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_M_CMUX CLBLM_LOGIC_OUTS22 IMUX40 CLBLM_M_D1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[37].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 IMUX35 CLBLM_M_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[38].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[39].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_D CLBLL_LOGIC_OUTS11 EL1BEG2 IMUX4 CLBLM_M_A6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[40].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_L_CMUX CLBLL_LOGIC_OUTS18 IMUX_L41 CLBLL_L_D1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[41].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_B CLBLL_LOGIC_OUTS9 IMUX_L34 CLBLL_L_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[42].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_A CLBLL_LOGIC_OUTS8 IMUX_L25 CLBLL_L_B5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[43].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_D CLBLL_LOGIC_OUTS15 EE2BEG3 WR1BEG_S0 WL1BEG2 IMUX_L6 CLBLL_L_A1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[44].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LL_CMUX CLBLL_LOGIC_OUTS22 NL1BEG_N3 IMUX_L38 CLBLL_LL_D3 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[45].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 IMUX_L35 CLBLL_LL_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[46].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[47].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_D CLBLM_LOGIC_OUTS11 EL1BEG2 IMUX_L4 CLBLL_LL_A6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[48].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10 IMUX37 CLBLM_L_D4 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[49].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 IMUX34 CLBLM_L_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[50].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 IMUX25 CLBLM_L_B5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[51].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_D CLBLM_M_DMUX CLBLM_LOGIC_OUTS23 IMUX3 CLBLM_L_A2 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[52].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_M_CMUX CLBLM_LOGIC_OUTS22 IMUX40 CLBLM_M_D1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[53].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 IMUX35 CLBLM_M_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[54].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 IMUX24 CLBLM_M_B5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[55].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_D CLBLL_LOGIC_OUTS11 EL1BEG2 IMUX4 CLBLM_M_A6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[56].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_L_CMUX CLBLL_LOGIC_OUTS18 IMUX_L41 CLBLL_L_D1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[57].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_B CLBLL_LOGIC_OUTS9 IMUX_L34 CLBLL_L_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[58].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_L_A CLBLL_L_AMUX CLBLL_LOGIC_OUTS16 IMUX_L13 CLBLL_L_B6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[59].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_D CLBLL_LL_DMUX CLBLL_LOGIC_OUTS23 IMUX_L3 CLBLL_L_A2 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[60].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LL_CMUX CLBLL_LOGIC_OUTS22 IMUX_L40 CLBLL_LL_D1 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[61].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 IMUX_L35 CLBLL_LL_C6 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[62].lut_coarse_delay_inst_clk/inv_data}]
set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 IMUX_L24 CLBLL_LL_B5 }  } [get_nets {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[63].lut_coarse_delay_inst_clk/inv_data}]

set_property LOC BUFGCTRL_X0Y0 [get_cells metastable_ro_i/clk_wiz_0/inst/clkout1_buf]
set_property FIXED_ROUTE { { CLK_BUFG_BUFGCTRL0_O CLK_BUFG_CK_GCLK0 CLK_BUFG_REBUF_R_CK_GCLK0_TOP CLK_BUFG_REBUF_R_CK_GCLK0_TOP CLK_BUFG_REBUF_R_CK_GCLK0_TOP CLK_HROW_CK_MUX_OUT_L0 CLK_HROW_CK_HCLK_OUT_L0 CLK_HROW_CK_BUFHCLK_L0 <3>HCLK_LEAF_CLK_B_BOT0 <24>GCLK_B0_WEST GFAN1  { BYP_ALT7 BYP_BOUNCE7 IMUX_L1 CLBLL_LL_A3 }  IMUX_L7 CLBLL_LL_A1 }  } [get_nets metastable_ro_i/clk_wiz_0/inst/clk_out1]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk2[63].lut_coarse_delay_inst_clk/LUT6_inst}]
set_property LOCK_PINS {I0:A3 I1:A1 I2:A2 I3:A4 I4:A5 I5:A6} [get_cells {metastable_ro_i/delay_top_0/inst/coarse_delay_inst/genblk1[63].lut_coarse_delay_inst_data/LUT6_inst}]


set_clock_groups -name grp1 -asynchronous -group [get_clocks clk_fpga_0] -group [get_clocks -of_objects [get_pins metastable_ro_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT1]]
set_clock_groups -name grp2 -asynchronous -group [get_clocks -of_objects [get_pins metastable_ro_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT0]] -group [get_clocks -of_objects [get_pins metastable_ro_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT1]]


