# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/meta.xdc

# Block Designs: bd/metastable_ro/metastable_ro.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro || ORIG_REF_NAME==metastable_ro}]

# IP: bd/metastable_ro/ip/metastable_ro_delay_top_0_0/metastable_ro_delay_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_delay_top_0_0 || ORIG_REF_NAME==metastable_ro_delay_top_0_0}]

# IP: bd/metastable_ro/ip/metastable_ro_processing_system7_0_0/metastable_ro_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_processing_system7_0_0 || ORIG_REF_NAME==metastable_ro_processing_system7_0_0}]

# IP: bd/metastable_ro/ip/metastable_ro_axi_gpio_0_0/metastable_ro_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_axi_gpio_0_0 || ORIG_REF_NAME==metastable_ro_axi_gpio_0_0}]

# IP: bd/metastable_ro/ip/metastable_ro_processing_system7_0_axi_periph_0/metastable_ro_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==metastable_ro_processing_system7_0_axi_periph_0}]

# IP: bd/metastable_ro/ip/metastable_ro_rst_processing_system7_0_100M_0/metastable_ro_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==metastable_ro_rst_processing_system7_0_100M_0}]

# IP: bd/metastable_ro/ip/metastable_ro_fine_delay_ctrl_0/metastable_ro_fine_delay_ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_fine_delay_ctrl_0 || ORIG_REF_NAME==metastable_ro_fine_delay_ctrl_0}]

# IP: bd/metastable_ro/ip/metastable_ro_xbar_0/metastable_ro_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_xbar_0 || ORIG_REF_NAME==metastable_ro_xbar_0}]

# IP: bd/metastable_ro/ip/metastable_ro_axi_gpio_0_1/metastable_ro_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_axi_gpio_0_1 || ORIG_REF_NAME==metastable_ro_axi_gpio_0_1}]

# IP: bd/metastable_ro/ip/metastable_ro_ila_0_0/metastable_ro_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_ila_0_0 || ORIG_REF_NAME==metastable_ro_ila_0_0}]

# IP: bd/metastable_ro/ip/metastable_ro_clk_wiz_0_0/metastable_ro_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_clk_wiz_0_0 || ORIG_REF_NAME==metastable_ro_clk_wiz_0_0}]

# IP: bd/metastable_ro/ip/metastable_ro_auto_pc_0/metastable_ro_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_auto_pc_0 || ORIG_REF_NAME==metastable_ro_auto_pc_0}]

# XDC: bd/metastable_ro/ip/metastable_ro_processing_system7_0_0/metastable_ro_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==metastable_ro_processing_system7_0_0 || ORIG_REF_NAME==metastable_ro_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/metastable_ro/ip/metastable_ro_axi_gpio_0_0/metastable_ro_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==metastable_ro_axi_gpio_0_0 || ORIG_REF_NAME==metastable_ro_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/metastable_ro/ip/metastable_ro_axi_gpio_0_0/metastable_ro_axi_gpio_0_0_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_axi_gpio_0_0/metastable_ro_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==metastable_ro_axi_gpio_0_0 || ORIG_REF_NAME==metastable_ro_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/metastable_ro/ip/metastable_ro_rst_processing_system7_0_100M_0/metastable_ro_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==metastable_ro_rst_processing_system7_0_100M_0}]

# XDC: bd/metastable_ro/ip/metastable_ro_rst_processing_system7_0_100M_0/metastable_ro_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==metastable_ro_rst_processing_system7_0_100M_0}]

# XDC: bd/metastable_ro/ip/metastable_ro_rst_processing_system7_0_100M_0/metastable_ro_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_fine_delay_ctrl_0/metastable_ro_fine_delay_ctrl_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==metastable_ro_fine_delay_ctrl_0 || ORIG_REF_NAME==metastable_ro_fine_delay_ctrl_0}] {/U0 }]/U0 ]]

# XDC: bd/metastable_ro/ip/metastable_ro_fine_delay_ctrl_0/metastable_ro_fine_delay_ctrl_0_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_fine_delay_ctrl_0/metastable_ro_fine_delay_ctrl_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==metastable_ro_fine_delay_ctrl_0 || ORIG_REF_NAME==metastable_ro_fine_delay_ctrl_0}] {/U0 }]/U0 ]]

# XDC: bd/metastable_ro/ip/metastable_ro_xbar_0/metastable_ro_xbar_0_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_axi_gpio_0_1/metastable_ro_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==metastable_ro_axi_gpio_0_1 || ORIG_REF_NAME==metastable_ro_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/metastable_ro/ip/metastable_ro_axi_gpio_0_1/metastable_ro_axi_gpio_0_1_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_axi_gpio_0_1/metastable_ro_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==metastable_ro_axi_gpio_0_1 || ORIG_REF_NAME==metastable_ro_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/metastable_ro/ip/metastable_ro_ila_0_0/ila_v5_0/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_ila_0_0 || ORIG_REF_NAME==metastable_ro_ila_0_0}]

# XDC: bd/metastable_ro/ip/metastable_ro_ila_0_0/metastable_ro_ila_0_0_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_clk_wiz_0_0/metastable_ro_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==metastable_ro_clk_wiz_0_0 || ORIG_REF_NAME==metastable_ro_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/metastable_ro/ip/metastable_ro_clk_wiz_0_0/metastable_ro_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==metastable_ro_clk_wiz_0_0 || ORIG_REF_NAME==metastable_ro_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/metastable_ro/ip/metastable_ro_clk_wiz_0_0/metastable_ro_clk_wiz_0_0_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_auto_pc_0/metastable_ro_auto_pc_0_ooc.xdc

# XDC: bd/metastable_ro/metastable_ro_ooc.xdc
