# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/meta.xdc

# Block Designs: bd/metastable_ro/metastable_ro.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro || ORIG_REF_NAME==metastable_ro}]

# IP: bd/metastable_ro/ip/metastable_ro_processing_system7_0_0/metastable_ro_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_processing_system7_0_0 || ORIG_REF_NAME==metastable_ro_processing_system7_0_0}]

# IP: bd/metastable_ro/ip/metastable_ro_rst_processing_system7_0_100M_0/metastable_ro_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==metastable_ro_rst_processing_system7_0_100M_0}]

# IP: bd/metastable_ro/ip/metastable_ro_clk_wiz_0_0/metastable_ro_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_clk_wiz_0_0 || ORIG_REF_NAME==metastable_ro_clk_wiz_0_0}]

# IP: bd/metastable_ro/ip/metastable_ro_processing_system7_0_axi_periph_1/metastable_ro_processing_system7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_processing_system7_0_axi_periph_1 || ORIG_REF_NAME==metastable_ro_processing_system7_0_axi_periph_1}]

# IP: bd/metastable_ro/ip/metastable_ro_axi_gpio_1_0/metastable_ro_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_axi_gpio_1_0 || ORIG_REF_NAME==metastable_ro_axi_gpio_1_0}]

# IP: bd/metastable_ro/ip/metastable_ro_axi_gpio_0_0/metastable_ro_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_axi_gpio_0_0 || ORIG_REF_NAME==metastable_ro_axi_gpio_0_0}]

# IP: bd/metastable_ro/ip/metastable_ro_xbar_0/metastable_ro_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_xbar_0 || ORIG_REF_NAME==metastable_ro_xbar_0}]

# IP: bd/metastable_ro/ip/metastable_ro_axi_gpio_0_2/metastable_ro_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_axi_gpio_0_2 || ORIG_REF_NAME==metastable_ro_axi_gpio_0_2}]

# IP: bd/metastable_ro/ip/metastable_ro_trng_control_0_0/metastable_ro_trng_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_trng_control_0_0 || ORIG_REF_NAME==metastable_ro_trng_control_0_0}]

# IP: bd/metastable_ro/ip/metastable_ro_lfsr_filter_0_0/metastable_ro_lfsr_filter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_lfsr_filter_0_0 || ORIG_REF_NAME==metastable_ro_lfsr_filter_0_0}]

# IP: bd/metastable_ro/ip/metastable_ro_xlconcat_0_0/metastable_ro_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_xlconcat_0_0 || ORIG_REF_NAME==metastable_ro_xlconcat_0_0}]

# IP: bd/metastable_ro/ip/metastable_ro_xlconstant_0_0/metastable_ro_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_xlconstant_0_0 || ORIG_REF_NAME==metastable_ro_xlconstant_0_0}]

# IP: bd/metastable_ro/ip/metastable_ro_bram_control_0_0/metastable_ro_bram_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_bram_control_0_0 || ORIG_REF_NAME==metastable_ro_bram_control_0_0}]

# IP: bd/metastable_ro/ip/metastable_ro_blk_mem_gen_0_0/metastable_ro_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_blk_mem_gen_0_0 || ORIG_REF_NAME==metastable_ro_blk_mem_gen_0_0}]

# IP: bd/metastable_ro/ip/metastable_ro_axi_bram_ctrl_0_0/metastable_ro_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_axi_bram_ctrl_0_0 || ORIG_REF_NAME==metastable_ro_axi_bram_ctrl_0_0}]

# IP: bd/metastable_ro/ip/metastable_ro_axi_gpio_1_1/metastable_ro_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_axi_gpio_1_1 || ORIG_REF_NAME==metastable_ro_axi_gpio_1_1}]

# IP: bd/metastable_ro/ip/metastable_ro_util_vector_logic_0_0/metastable_ro_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_util_vector_logic_0_0 || ORIG_REF_NAME==metastable_ro_util_vector_logic_0_0}]

# IP: bd/metastable_ro/ip/metastable_ro_delay_top_0_1/metastable_ro_delay_top_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_delay_top_0_1 || ORIG_REF_NAME==metastable_ro_delay_top_0_1}]

# IP: bd/metastable_ro/ip/metastable_ro_util_vector_logic_0_1/metastable_ro_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_util_vector_logic_0_1 || ORIG_REF_NAME==metastable_ro_util_vector_logic_0_1}]

# IP: bd/metastable_ro/ip/metastable_ro_util_vector_logic_0_2/metastable_ro_util_vector_logic_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_util_vector_logic_0_2 || ORIG_REF_NAME==metastable_ro_util_vector_logic_0_2}]

# IP: bd/metastable_ro/ip/metastable_ro_util_vector_logic_0_3/metastable_ro_util_vector_logic_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_util_vector_logic_0_3 || ORIG_REF_NAME==metastable_ro_util_vector_logic_0_3}]

# IP: bd/metastable_ro/ip/metastable_ro_util_vector_logic_1_0/metastable_ro_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_util_vector_logic_1_0 || ORIG_REF_NAME==metastable_ro_util_vector_logic_1_0}]

# IP: bd/metastable_ro/ip/metastable_ro_mux_s0_0/metastable_ro_mux_s0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_mux_s0_0 || ORIG_REF_NAME==metastable_ro_mux_s0_0}]

# IP: bd/metastable_ro/ip/metastable_ro_util_vector_logic_1_1/metastable_ro_util_vector_logic_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_util_vector_logic_1_1 || ORIG_REF_NAME==metastable_ro_util_vector_logic_1_1}]

# IP: bd/metastable_ro/ip/metastable_ro_util_vector_logic_2_0/metastable_ro_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_util_vector_logic_2_0 || ORIG_REF_NAME==metastable_ro_util_vector_logic_2_0}]

# IP: bd/metastable_ro/ip/metastable_ro_xlconstant_1_0/metastable_ro_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_xlconstant_1_0 || ORIG_REF_NAME==metastable_ro_xlconstant_1_0}]

# IP: bd/metastable_ro/ip/metastable_ro_xlconcat_1_0/metastable_ro_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_xlconcat_1_0 || ORIG_REF_NAME==metastable_ro_xlconcat_1_0}]

# IP: bd/metastable_ro/ip/metastable_ro_xlconstant_1_1/metastable_ro_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_xlconstant_1_1 || ORIG_REF_NAME==metastable_ro_xlconstant_1_1}]

# IP: bd/metastable_ro/ip/metastable_ro_xlconcat_1_1/metastable_ro_xlconcat_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_xlconcat_1_1 || ORIG_REF_NAME==metastable_ro_xlconcat_1_1}]

# IP: bd/metastable_ro/ip/metastable_ro_util_vector_logic_1_2/metastable_ro_util_vector_logic_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_util_vector_logic_1_2 || ORIG_REF_NAME==metastable_ro_util_vector_logic_1_2}]

# IP: bd/metastable_ro/ip/metastable_ro_util_vector_logic_1_3/metastable_ro_util_vector_logic_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_util_vector_logic_1_3 || ORIG_REF_NAME==metastable_ro_util_vector_logic_1_3}]

# IP: bd/metastable_ro/ip/metastable_ro_util_vector_logic_1_4/metastable_ro_util_vector_logic_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_util_vector_logic_1_4 || ORIG_REF_NAME==metastable_ro_util_vector_logic_1_4}]

# IP: bd/metastable_ro/ip/metastable_ro_util_vector_logic_1_5/metastable_ro_util_vector_logic_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_util_vector_logic_1_5 || ORIG_REF_NAME==metastable_ro_util_vector_logic_1_5}]

# IP: bd/metastable_ro/ip/metastable_ro_not_s_equals0_0/metastable_ro_not_s_equals0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_not_s_equals0_0 || ORIG_REF_NAME==metastable_ro_not_s_equals0_0}]

# IP: bd/metastable_ro/ip/metastable_ro_util_vector_logic_1_6/metastable_ro_util_vector_logic_1_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_util_vector_logic_1_6 || ORIG_REF_NAME==metastable_ro_util_vector_logic_1_6}]

# IP: bd/metastable_ro/ip/metastable_ro_MUX_SELECT_OR_0/metastable_ro_MUX_SELECT_OR_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_MUX_SELECT_OR_0 || ORIG_REF_NAME==metastable_ro_MUX_SELECT_OR_0}]

# IP: bd/metastable_ro/ip/metastable_ro_xlconstant_3_0/metastable_ro_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_xlconstant_3_0 || ORIG_REF_NAME==metastable_ro_xlconstant_3_0}]

# IP: bd/metastable_ro/ip/metastable_ro_xlconcat_1_2/metastable_ro_xlconcat_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_xlconcat_1_2 || ORIG_REF_NAME==metastable_ro_xlconcat_1_2}]

# IP: bd/metastable_ro/ip/metastable_ro_xlconcat_1_3/metastable_ro_xlconcat_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_xlconcat_1_3 || ORIG_REF_NAME==metastable_ro_xlconcat_1_3}]

# IP: bd/metastable_ro/ip/metastable_ro_PI_controller_0_0/metastable_ro_PI_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_PI_controller_0_0 || ORIG_REF_NAME==metastable_ro_PI_controller_0_0}]

# IP: bd/metastable_ro/ip/metastable_ro_c_shift_ram_0_0/metastable_ro_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_c_shift_ram_0_0 || ORIG_REF_NAME==metastable_ro_c_shift_ram_0_0}]

# IP: bd/metastable_ro/ip/metastable_ro_auto_pc_0/metastable_ro_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_auto_pc_0 || ORIG_REF_NAME==metastable_ro_auto_pc_0}]

# IP: bd/metastable_ro/ip/metastable_ro_auto_pc_1/metastable_ro_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_auto_pc_1 || ORIG_REF_NAME==metastable_ro_auto_pc_1}]

# IP: bd/metastable_ro/ip/metastable_ro_auto_pc_2/metastable_ro_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_auto_pc_2 || ORIG_REF_NAME==metastable_ro_auto_pc_2}]

# IP: bd/metastable_ro/ip/metastable_ro_auto_pc_3/metastable_ro_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_auto_pc_3 || ORIG_REF_NAME==metastable_ro_auto_pc_3}]

# IP: bd/metastable_ro/ip/metastable_ro_auto_pc_4/metastable_ro_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_auto_pc_4 || ORIG_REF_NAME==metastable_ro_auto_pc_4}]

# XDC: bd/metastable_ro/ip/metastable_ro_processing_system7_0_0/metastable_ro_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==metastable_ro_processing_system7_0_0 || ORIG_REF_NAME==metastable_ro_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/metastable_ro/ip/metastable_ro_rst_processing_system7_0_100M_0/metastable_ro_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==metastable_ro_rst_processing_system7_0_100M_0}]

# XDC: bd/metastable_ro/ip/metastable_ro_rst_processing_system7_0_100M_0/metastable_ro_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==metastable_ro_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==metastable_ro_rst_processing_system7_0_100M_0}]

# XDC: bd/metastable_ro/ip/metastable_ro_rst_processing_system7_0_100M_0/metastable_ro_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_clk_wiz_0_0/metastable_ro_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==metastable_ro_clk_wiz_0_0 || ORIG_REF_NAME==metastable_ro_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/metastable_ro/ip/metastable_ro_clk_wiz_0_0/metastable_ro_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==metastable_ro_clk_wiz_0_0 || ORIG_REF_NAME==metastable_ro_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/metastable_ro/ip/metastable_ro_clk_wiz_0_0/metastable_ro_clk_wiz_0_0_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_axi_gpio_1_0/metastable_ro_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==metastable_ro_axi_gpio_1_0 || ORIG_REF_NAME==metastable_ro_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/metastable_ro/ip/metastable_ro_axi_gpio_1_0/metastable_ro_axi_gpio_1_0_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_axi_gpio_1_0/metastable_ro_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==metastable_ro_axi_gpio_1_0 || ORIG_REF_NAME==metastable_ro_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/metastable_ro/ip/metastable_ro_axi_gpio_0_0/metastable_ro_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==metastable_ro_axi_gpio_0_0 || ORIG_REF_NAME==metastable_ro_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/metastable_ro/ip/metastable_ro_axi_gpio_0_0/metastable_ro_axi_gpio_0_0_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_axi_gpio_0_0/metastable_ro_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==metastable_ro_axi_gpio_0_0 || ORIG_REF_NAME==metastable_ro_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/metastable_ro/ip/metastable_ro_xbar_0/metastable_ro_xbar_0_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_axi_gpio_0_2/metastable_ro_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==metastable_ro_axi_gpio_0_2 || ORIG_REF_NAME==metastable_ro_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/metastable_ro/ip/metastable_ro_axi_gpio_0_2/metastable_ro_axi_gpio_0_2_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_axi_gpio_0_2/metastable_ro_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==metastable_ro_axi_gpio_0_2 || ORIG_REF_NAME==metastable_ro_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/metastable_ro/ip/metastable_ro_blk_mem_gen_0_0/metastable_ro_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_axi_bram_ctrl_0_0/metastable_ro_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_axi_gpio_1_1/metastable_ro_axi_gpio_1_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==metastable_ro_axi_gpio_1_1 || ORIG_REF_NAME==metastable_ro_axi_gpio_1_1}] {/U0 }]/U0 ]]

# XDC: bd/metastable_ro/ip/metastable_ro_axi_gpio_1_1/metastable_ro_axi_gpio_1_1_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_axi_gpio_1_1/metastable_ro_axi_gpio_1_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==metastable_ro_axi_gpio_1_1 || ORIG_REF_NAME==metastable_ro_axi_gpio_1_1}] {/U0 }]/U0 ]]

# XDC: bd/metastable_ro/ip/metastable_ro_c_shift_ram_0_0/metastable_ro_c_shift_ram_0_0_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_auto_pc_0/metastable_ro_auto_pc_0_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_auto_pc_1/metastable_ro_auto_pc_1_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_auto_pc_2/metastable_ro_auto_pc_2_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_auto_pc_3/metastable_ro_auto_pc_3_ooc.xdc

# XDC: bd/metastable_ro/ip/metastable_ro_auto_pc_4/metastable_ro_auto_pc_4_ooc.xdc

# XDC: bd/metastable_ro/metastable_ro_ooc.xdc
